export enum ActionTypes {

    PRODUCT_SET                 = '[PRODUCT] PRODUCT_SET',
    PRODUCT_CLEAR               = '[PRODUCT] PRODUCT_CLEAR',

    PRODUCTCATALOG_SET          = '[PRODUCTCATALOG] PRODUCTCATALOG_SET',
    PRODUCTCATALOG_CLEAR        = '[PRODUCTCATALOG] PRODUCTCATALOG_CLEAR',

    SHOPPINGCART_ADD            = '[SHOPPINGCART] SHOPPINGCART_ADD',
    SHOPPINGCART_DELETE         = '[SHOPPINGCART] SHOPPINGCART_DELETE',
    SHOPPINGCART_INCREMENT      = '[SHOPPINGCART] SHOPPINGCART_INCREMENT',
    SHOPPINGCART_DECREMENT      = '[SHOPPINGCART] SHOPPINGCART_DECREMENT',
    SHOPPINGCART_CLEAR          = '[SHOPPINGCART] SHOPPINGCART_CLEAR',

    USER_SET                    = '[USER] USER_SET',
    USER_LOGOUT                 = '[USER] USER_LOGOUT',

    ORDER_SET                   = '[ORDER] ORDER_SET'

}